apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      key: node1
  template:
    metadata:
     labels:
      key: node1
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        key: node1
